- todo-vue-pwa/src/App.vue
- todo-vue-pwa/src/components/Todo.vue
- todo-vue-pwa/src/components/features/Form.vue
- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/components/shared/Footer.vue
- todo-vue-pwa/src/components/shared/Header.vue
> Create component for app

- todo-vue-pwa/src/assets/styling/pages/_all.scss
- todo-vue-pwa/src/assets/styling/pages/_form.scss
- todo-vue-pwa/src/components/features/Form.vue
> Making UI for form

- todo-vue-pwa/src/assets/styling/base/_variables.scss
- todo-vue-pwa/src/assets/styling/modules/_all.scss
- todo-vue-pwa/src/assets/styling/modules/_checkbox.scss
- todo-vue-pwa/src/assets/styling/pages/_all.scss
- todo-vue-pwa/src/assets/styling/pages/_form.scss
- todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
- todo-vue-pwa/src/components/features/Form.vue
- todo-vue-pwa/src/components/features/ListTodo.vue
> Making UI for list todo

- todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/store/getters.ts
- todo-vue-pwa/src/store/state.ts
> Implement logic for list todo

- todo-vue-pwa/src/components/features/Form.vue
- todo-vue-pwa/src/store/actions.ts
- todo-vue-pwa/src/store/mutations.ts
> Implement logic for add new

- todo-vue-pwa/src/assets/styling/modules/_buttons.scss
- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/components/shared/Footer.vue
- todo-vue-pwa/src/store/actions.ts
- todo-vue-pwa/src/store/getters.ts
- todo-vue-pwa/src/store/mutations.ts
- todo-vue-pwa/src/store/state.ts
> Implement filter

- todo-vue-pwa/src/assets/styling/modules/_buttons.scss
- todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/store/state.ts
- Show message no task
- Show total item
> Show message no task

- todo-vue-pwa/src/assets/styling/modules/_buttons.scss
- todo-vue-pwa/src/components/features/Form.vue
- todo-vue-pwa/src/components/shared/Footer.vue
Disabled button if it is current filter
> Disabled button if it is current filter

- todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
- todo-vue-pwa/src/components/features/ListTodo.vue
> Add transition

- todo-vue-pwa/src/components/features/ListTodo.vue
> Change text total task

- todo-vue-pwa/src/components/features/ListTodo.vue
> Change id of item

- todo-vue-pwa/src/assets/styling/layout/_footer.scss
- todo-vue-pwa/src/assets/styling/pages/_form.scss
- todo-vue-pwa/src/components/features/Form.vue
- todo-vue-pwa/src/components/shared/Footer.vue
> Update UI for app

- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/store/actions.ts
- todo-vue-pwa/src/store/mutations.ts
> [Logic] Update status logic

- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/store/actions.ts
- todo-vue-pwa/src/store/mutations.ts
> [Logic] Remove todo

- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/components/shared/Footer.vue
- todo-vue-pwa/src/store/actions.ts
- todo-vue-pwa/src/store/getters.ts
- todo-vue-pwa/src/store/mutations.ts
> Remove completed

- todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
- todo-vue-pwa/src/store/mutations.ts
> Change animation

- todo-vue-pwa/src/assets/styling/base/_base.scss
- todo-vue-pwa/src/assets/styling/base/_variables.scss
- todo-vue-pwa/src/assets/styling/layout/_footer.scss
- todo-vue-pwa/src/assets/styling/layout/_header.scss
- todo-vue-pwa/src/assets/styling/layout/_layout.scss
- todo-vue-pwa/src/assets/styling/pages/_list-todo.scss
- todo-vue-pwa/src/components/features/Form.vue
- todo-vue-pwa/src/store/mutations.ts
> [Task] [UI] Responsive on desktop view

- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/store/actions.ts
- todo-vue-pwa/src/store/getters.ts
- todo-vue-pwa/src/store/mutations.ts
- todo-vue-pwa/src/store/state.ts
Using firebase to add, update, delete, remove
> Using firebase to add, update, delete, remove

- todo-vue-pwa/src/App.vue
- todo-vue-pwa/src/assets/styling/modules/_all.scss
- todo-vue-pwa/src/assets/styling/modules/_loading.scss
- todo-vue-pwa/src/assets/styling/pages/_auth.scss
- todo-vue-pwa/src/components/features/ListTodo.vue
- todo-vue-pwa/src/components/features/SignIn.vue
- todo-vue-pwa/src/components/features/SignUp.vue
- todo-vue-pwa/src/components/shared/Loading.vue
> Add loading screen

- todo-vue-pwa/src/store/mutations.ts
> Order by created date
